#!/bin/sh

# From https://unix.stackexchange.com/a/567213
# TODO: explore this one more: https://unix.stackexchange.com/a/449013

dbus-monitor --session "type='signal',interface='org.cinnamon.ScreenSaver'" | \
(
  while true; do
    read X
    if echo $X | grep "boolean false" &> /dev/null; then
      sleep 5; xdotool key XF86MonBrightnessDown
    fi
  done
)
