#!/bin/bash

# From https://unix.stackexchange.com/a/449013
# and https://github.com/gogama/lockheed/blob/main/lockheed#L206-L217

gdbus monitor -y -d org.freedesktop.login1 |
  grep --line-buffered -o '<false>' |
  while read -r; do
    xdotool key XF86MonBrightnessDown
  done
