#!/bin/bash

# Does an inplace (-i) edit of /boot/grub/grub.cfg replacing 30-second with 2-second timeouts, and backs up the original with an extension ".backup.daily".

cp /boot/grub/grub.cfg /boot/grub/grub.cfg.backup.daily
sed -i 's/^  set timeout=30$/  set timeout=2/g' /boot/grub/grub.cfg
