#!/bin/bash

# Sets the key repeat delay to a (probably) slightly different value.
# Run this via a keyboard shortcut whenever the repeat delay mysteriously
# gets longer.

value=$((300+$RANDOM%20))
gsettings set org.cinnamon.desktop.peripherals.keyboard delay $value
